--名称
appname="测试程序"
--版本号
appver="免费开源项目"
--版本
appcode="99699699"
--SDK
appsdk="15"
--包名
packagename="com.tencent.mfkyzs"
--调试模式
debugmode=false
--应用权限
user_permission={
  "ACCESS_MEDIA_LOCATION",
  "ACCESS_NETWORK_STATE",
  "ACCESS_WIFI_STATE",
  "CHANGE_NETWORK_STATE",
  "CHANGE_WIFI_STATE",
  "GET_PACKAGE_SIZE",
  "GET_TASKS",
  "INSTALL_SHORTCUT",
  "INTERNET",
  "KILL_BACKGROUND_PROCESSES",
  "READ_EXTERNAL_STORAGE",
  "READ_PHONE_STATE",
  "REQUEST_INSTALL_PACKAGES",
  "SYSTEM_ALERT_WINDOW",
  "WRITE_EXTERNAL_STORAGE",
  "WRITE_SETTINGS",
}
--跳过编译
skip_compilation={

}